name: Met-Ke-Dede

on: [push]

defaults:
  run:
    shell: bash -l {0}

jobs:
  code_check:
    name: Build Wheel Artifact
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: baz.yml
          miniconda-version: "latest"
          activate-environment: base
          python-version: 3.9
          channels: conda-forge
          auto-activate-base: true
      - run: |
          conda info
          conda list
          poetry install
          poetry show --tree
          make test
